### ISSUE TITLE
Different result data format 

### ISSUE THREAD

**Issue by zgeist** [artf/grapesjs-parser-postcss#6]
PostCss and BrowserCssParser in base grapesjs return different data format

PostCss example
```
{
       selectors: '.selector',
       styles: '....',
       atRule: '.....',
       params: '.....'
}
```

Browser
```
{
         selectors: [],
         selectorsAdd: '.selector',
         style: '...',
         atRuleText: '.....',
         mediaText: '.....'
}
```

Could you plan to unificate formats?

Have some problems when I try add content in components like 
It sometimes drop media query or some styles
```
this.model.replaceWith('<div class="test">Test</div><style>.test {}</style>')

```

**Comment by artf** [comment]
The editor always returns its internal structure (the "Browser" example), the one you're showing as "PostCss" is made on purpose different for CSS parsers in order to facilitate creating custom CSS parsers for the editor (using one only format right now it's not an option).

Please create a reproducible demo of your issue if you believe there is a bug.
